// Hình học riêng cho tám chưởng. Không tải ảnh hiệu ứng; mọi màu đọc từ cấu hình.
import type {SacChuong} from './kieu'
type C=CanvasRenderingContext2D
type P={x:number;y:number}

const TAU=Math.PI*2,clamp=(x:number)=>Math.max(0,Math.min(1,x));
export function rgba(color:string,a:number){return color.replace('rgb(', 'rgba(').replace(')',','+a+')')}
function path(ctx:C,pts:number[][],fill:string|CanvasGradient|null,stroke:string|null=null,width=2){ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
function glow(c:C,x:number,y:number,r:number,color:string,a=1){if(r<=0||a<=0)return;const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,rgba('rgb(255,255,255)',a*.7));g.addColorStop(.18,rgba(color,a*.82));g.addColorStop(.56,rgba(color,a*.25));g.addColorStop(1,rgba(color,0));c.fillStyle=g;c.beginPath();c.arc(x,y,r,0,TAU);c.fill()}
function ring(c:C,x:number,y:number,r:number,color:string,a=1,flat=1,width=2,rot=0){c.save();c.globalAlpha=a;c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.ellipse(x,y,r,r*flat,rot,0,TAU);c.stroke();c.restore()}
function star(c:C,x:number,y:number,r:number,color:string,angle=0,points=4){c.save();c.translate(x,y);c.rotate(angle);const ps=[];for(let i=0;i<points*2;i++){const a=i*Math.PI/points-Math.PI/2,d=i%2?r*.25:r;ps.push([Math.cos(a)*d,Math.sin(a)*d])}path(c,ps,color);c.restore()}
function leaf(c:C,x:number,y:number,size:number,color:string,rot:number){c.save();c.translate(x,y);c.rotate(rot);c.fillStyle=color;c.beginPath();c.moveTo(-size,0);c.quadraticCurveTo(0,-size*.85,size,0);c.quadraticCurveTo(0,size*.8,-size,0);c.fill();c.strokeStyle='rgba(255,255,235,.65)';c.lineWidth=1;c.beginPath();c.moveTo(-size*.65,0);c.lineTo(size*.7,0);c.stroke();c.restore()}
function flower(c:C,x:number,y:number,r:number,skin:SacChuong,rot=0){c.save();c.translate(x,y);c.rotate(rot);for(let i=0;i<5;i++){c.save();c.rotate(i*TAU/5);c.fillStyle=i%2?skin.main:skin.accent;c.beginPath();c.ellipse(0,-r*.53,r*.3,r*.55,0,0,TAU);c.fill();c.restore()}glow(c,0,0,r*.35,skin.accent,1);c.restore()}
function crystal(c:C,x:number,y:number,r:number,skin:SacChuong,rot=0){c.save();c.translate(x,y);c.rotate(rot);path(c,[[-r*.72,0],[-r*.16,-r*.78],[r*.73,-r*.08],[r*.15,r*.82]],skin.main,skin.accent,2);path(c,[[-r*.72,0],[-r*.16,-r*.78],[0,0]],skin.accent);path(c,[[0,0],[r*.73,-r*.08],[r*.15,r*.82]],rgba('rgb(255,255,255)',.18));c.restore()}
function feather(c:C,x:number,y:number,r:number,skin:SacChuong,rot:number){c.save();c.translate(x,y);c.rotate(rot);path(c,[[-r*.75,0],[r*.18,-r*.28],[r,0],[r*.18,r*.28]],skin.main,skin.accent,1);c.strokeStyle='rgb(255,253,243)';c.lineWidth=1;c.beginPath();c.moveTo(-r*.55,0);c.lineTo(r*.77,0);c.stroke();c.restore()}
function particles(c:C,x:number,y:number,t:number,skin:SacChuong,ult:boolean,light:boolean,charge=false){const n=light?7:ult?42:24;c.save();c.globalCompositeOperation='lighter';for(let i=0;i<n;i++){const a=i*2.399963+(charge?t*3:0),fraction=.35+.65*((i*37)%97)/97,r=charge?(1-t)*105*fraction+11:(28+t*(ult?185:125))*fraction,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r*.74+(charge?0:t*t*28);const alpha=charge?.35+t*.55:Math.pow(1-t,1.25);c.globalAlpha=alpha;const size=(i%4===0?6:3)*(charge?.5+t*.4:1-t*.7);if(skin.type==='flower'&&i%3===0)flower(c,px,py,size*1.5,skin,a+t*4);else if((skin.type==='wind'||skin.type==='vine')&&i%3===0)leaf(c,px,py,size*1.8,i%2?skin.main:skin.accent,a+t*4);else if(skin.type==='crystal'&&i%4===0)crystal(c,px,py,size*1.3,skin,a);else star(c,px,py,size,i%2?skin.main:skin.accent,a,4)}c.restore()}
function motif(c:C,skin:SacChuong,x:number,y:number,r:number,time:number){c.save();c.translate(x,y);c.globalCompositeOperation='source-over';
if(skin.type==='crystal'){glow(c,0,0,r*1.9,skin.main,.85);crystal(c,0,0,r,skin,time*.22);for(let i=0;i<3;i++){const a=time*2+i*TAU/3;crystal(c,Math.cos(a)*r*1.35,Math.sin(a)*r*.65,r*.23,skin,a)}}
else if(skin.type==='water'){glow(c,0,0,r*1.6,skin.main,.8);for(let i=0;i<3;i++){const a=time*3+i*TAU/3;c.save();c.rotate(a);c.strokeStyle=i===1?skin.accent:skin.main;c.lineWidth=r*.12;c.beginPath();c.ellipse(0,0,r,r*.44,0,-.45,Math.PI*1.15);c.stroke();c.restore()}glow(c,0,0,r*.65,skin.accent,1)}
else if(skin.type==='fire'){glow(c,0,0,r*1.9,skin.main,.8);for(let i=0;i<7;i++){c.save();c.rotate(time*2.2+i*TAU/7);const g=c.createLinearGradient(0,-r*1.4,0,r*.3);g.addColorStop(0,rgba(skin.main,0));g.addColorStop(.3,skin.main);g.addColorStop(1,skin.accent);c.fillStyle=g;c.beginPath();c.moveTo(-r*.13,-r*.1);c.quadraticCurveTo(-r*.7,-r*.8,r*.22,-r*1.45);c.quadraticCurveTo(-r*.04,-r*.55,r*.22,0);c.closePath();c.fill();c.restore()}glow(c,0,0,r*.7,skin.accent,1)}
else if(skin.type==='wind'){glow(c,0,0,r*1.5,skin.main,.6);for(let i=0;i<3;i++){c.save();c.rotate(-time*4+i*TAU/3);c.fillStyle=i===1?skin.accent:skin.main;c.beginPath();c.moveTo(-r*.1,-r*.12);c.quadraticCurveTo(r*.1,-r*1.75,r*1.32,-r*.6);c.quadraticCurveTo(r*.65,-r*.8,r*.3,r*.12);c.closePath();c.fill();c.restore()}star(c,0,0,r*.4,'rgb(246,255,233)',time*2,4)}
else if(skin.type==='star'){glow(c,0,0,r*2,skin.main,.7);const p:number[][]=[];for(let i=0;i<5;i++){const a=-time+i*TAU/5-Math.PI/2;p.push([Math.cos(a)*r,Math.sin(a)*r]);star(c,p[i][0],p[i][1],r*.22,skin.accent,time)}c.strokeStyle=skin.main;c.lineWidth=2;c.beginPath();[0,2,4,1,3,0].forEach((id,i)=>i?c.lineTo(p[id][0],p[id][1]):c.moveTo(p[id][0],p[id][1]));c.stroke();star(c,0,0,r*.64,skin.accent,-time,4)}
else if(skin.type==='flower'){glow(c,0,0,r*1.9,skin.main,.75);flower(c,0,0,r,skin,time*.7);ring(c,0,0,r*1.22,skin.accent,.72,1,1.7);for(let i=0;i<5;i++){const a=time*1.7+i*TAU/5;star(c,Math.cos(a)*r*1.35,Math.sin(a)*r*1.35,3.3,skin.accent,a)}}
else if(skin.type==='vine'){glow(c,0,0,r*1.7,skin.main,.65);for(let i=0;i<5;i++){const a=time*1.4+i*TAU/5;leaf(c,Math.cos(a)*r*.75,Math.sin(a)*r*.75,r*.53,skin.main,a+Math.PI/2)}flower(c,0,0,r*.48,skin,-time*.7)}
else{glow(c,0,0,r*2.2,skin.main,.82);for(let i=0;i<4;i++){const a=time*.8+i*TAU/4;feather(c,Math.cos(a)*r*.8,Math.sin(a)*r*.8,r*.74,skin,a)}star(c,0,0,r*.72,skin.accent,-time*.8,4);ring(c,0,0,r*1.1,skin.accent,.66,1,1.5)}
c.restore()}
function trail(c:C,skin:SacChuong,x:number,y:number,source:P,_p:number,r:number,time:number,light:boolean){c.save();c.globalCompositeOperation='lighter';const length=Math.min(160,Math.max(25,x-source.x));const g=c.createLinearGradient(x-length,y,x,y);g.addColorStop(0,rgba(skin.main,0));g.addColorStop(.8,rgba(skin.main,.65));g.addColorStop(1,skin.accent);c.lineCap='round';
if(skin.type==='water'){for(let i=0;i<(light?1:3);i++){c.strokeStyle=g;c.lineWidth=r*.13;c.beginPath();for(let k=0;k<=16;k++){const xx=x-length+k*length/16,yy=y+Math.sin(k*.4-time*10+i*TAU/3)*r*.38*(k/16);if(k)c.lineTo(xx,yy);else c.moveTo(xx,yy)}c.stroke()}}
else if(skin.type==='vine'){c.strokeStyle=g;c.lineWidth=r*.1;c.beginPath();c.moveTo(x-length,y+9);c.bezierCurveTo(x-length*.65,y-22,x-length*.25,y+25,x,y);c.stroke();for(let i=0;i<4;i++)leaf(c,x-i*length/5,y+Math.sin(i*1.5+time*3)*13,r*.21,skin.main,i)}
else if(skin.type==='light'){c.fillStyle=g;path(c,[[x-length,y],[x-8,y-r*.22],[x+6,y],[x-8,y+r*.22]],g);if(!light)for(let i=1;i<4;i++)feather(c,x-i*length/4,y+Math.sin(i*2)*r*.3,r*.28,skin,0)}
else{c.strokeStyle=g;c.lineWidth=r*.31;c.beginPath();c.moveTo(x-length,y+8);c.quadraticCurveTo(x-length*.45,y-r*.18,x,y);c.stroke();if(!light)for(let i=1;i<5;i++){c.globalAlpha=(1-i/5)*.6;const xx=x-i*length/5,yy=y+Math.sin(i*1.6-time*5)*r*.26;if(skin.type==='flower')flower(c,xx,yy,r*.17,skin,time+i);else if(skin.type==='wind')leaf(c,xx,yy,r*.25,skin.main,time+i);else if(skin.type==='crystal')crystal(c,xx,yy,r*.16,skin,time);else star(c,xx,yy,3,skin.accent,time)}}c.restore()}
function charge(c:C,skin:SacChuong,source:P,ground:number,t:number,time:number,ult:boolean,light:boolean){const r=10+t*(ult?39:26);c.save();c.globalCompositeOperation='lighter';glow(c,source.x,source.y,58+t*(ult?70:36),skin.main,.25+t*.35);ring(c,source.x,source.y,r+25*(1-t),skin.accent,.6,.83,1.5,time*.5);ring(c,source.x,source.y,r*1.27,skin.main,.65,.87,1.5,-time);ring(c,source.x-42,ground+3,42+t*(ult?85:50),skin.main,.45,.18,2);if(ult&&!light)ring(c,source.x-42,ground+3,80+t*80,skin.accent,.5,.18,1.5);particles(c,source.x,source.y,t,skin,ult,light,true);motif(c,skin,source.x,source.y,r,time);c.restore()}
function impact(c:C,skin:SacChuong,target:P,t:number,time:number,ult:boolean,light:boolean){const maxR=ult?180:125;c.save();c.globalCompositeOperation='lighter';glow(c,target.x,target.y,(ult?120:84)*(1-t),skin.main,(1-t)*.88);for(let i=0;i<(light?1:3);i++){const d=clamp(t-i*.1);ring(c,target.x,target.y,18+d*maxR,i%2?skin.accent:skin.main,(1-d)*.9,.76,Math.max(1,5*(1-d)))}
if(skin.type==='crystal'){for(let i=0;i<(light?3:7);i++){const a=i*TAU/7;crystal(c,target.x+Math.cos(a)*t*maxR,target.y+Math.sin(a)*t*maxR*.7,20*(1-t),skin,a)}}
else if(skin.type==='water'){for(let i=0;i<(light?3:9);i++){const a=i*TAU/9,x=target.x+Math.cos(a)*t*maxR,y=target.y+Math.sin(a)*t*maxR*.7;c.save();c.translate(x,y);c.rotate(a+Math.PI/2);c.fillStyle=i%2?skin.main:skin.accent;const r=13*(1-t);c.beginPath();c.moveTo(0,-r*1.6);c.bezierCurveTo(r,r*.1,r,r,0,r);c.bezierCurveTo(-r,r,-r,r*.1,0,-r*1.6);c.fill();c.restore()}ring(c,target.x,target.y+30,25+t*maxR,skin.accent,1-t,.23,2)}
else if(skin.type==='fire'){for(let i=0;i<(light?3:9);i++){const a=i*TAU/9,x=target.x+Math.cos(a)*t*maxR,y=target.y+Math.sin(a)*t*maxR*.7;c.save();c.translate(x,y);c.rotate(a+Math.PI/2);const r=20*(1-t);c.fillStyle=skin.main;c.beginPath();c.moveTo(0,r);c.bezierCurveTo(-r,-r*.1,-r*.4,-r*.8,r*.2,-r*1.6);c.quadraticCurveTo(r*.85,-r*.15,0,r);c.fill();c.fillStyle=skin.accent;c.beginPath();c.ellipse(0,r*.1,r*.21,r*.6,-.15,0,TAU);c.fill();c.restore()}}
else if(skin.type==='wind'){for(let i=0;i<(light?2:5);i++){const a=i*TAU/5+time*1.3;leaf(c,target.x+Math.cos(a)*t*maxR,target.y+Math.sin(a)*t*maxR*.7,17*(1-t),skin.main,a)}}
else if(skin.type==='flower'||skin.type==='vine'){if(t<.58)flower(c,target.x,target.y,(ult?80:58)*Math.sin(clamp(t/.58)*Math.PI),skin,time);for(let i=0;i<(light?3:8);i++){const a=i*TAU/8;const x=target.x+Math.cos(a)*t*maxR,y=target.y+Math.sin(a)*t*maxR*.7;if(skin.type==='flower')flower(c,x,y,12*(1-t),skin,a);else leaf(c,x,y,18*(1-t),skin.main,a)}}
else if(skin.type==='star'){const points:number[][]=[];for(let i=0;i<5;i++){const a=i*TAU/5-Math.PI/2;points.push([target.x+Math.cos(a)*(30+t*maxR),target.y+Math.sin(a)*(30+t*maxR)*.75]);star(c,points[i][0],points[i][1],11*(1-t),skin.accent,time)}c.strokeStyle=rgba(skin.main,(1-t)*.65);c.lineWidth=1.5;c.beginPath();[0,2,4,1,3,0].forEach((id,i)=>i?c.lineTo(points[id][0],points[id][1]):c.moveTo(points[id][0],points[id][1]));c.stroke()}
else if(skin.type==='light'){for(let i=0;i<(light?3:8);i++){const a=i*TAU/8;feather(c,target.x+Math.cos(a)*t*maxR,target.y+Math.sin(a)*t*maxR*.75,27*(1-t),skin,a)}}
particles(c,target.x,target.y,t,skin,ult,light);c.restore()}
export function veChuong(c:C,{skin,time,source,target,ground,ultimate=false,light=false,layer='all'}:{skin:SacChuong;time:number;source:P;target:P;ground:number;ultimate?:boolean;light?:boolean;layer?:'all'|'behind'|'front'}){const release=ultimate?.96:.63,travel=ultimate?.62:.49,hit=release+travel,finish=ultimate?3.05:2.16;let phase='Tụ lực',fraction=clamp(time/finish),impactT=null,shake=0;
if(time<release){if(layer==='all'||layer==='behind')charge(c,skin,source,ground,clamp(time/release),time,ultimate,light)}else if(time<hit){phase='Phóng';const p=clamp((time-release)/travel),x=source.x+(target.x-source.x)*p,y=source.y+(target.y-source.y)*p-Math.sin(p*Math.PI)*(ultimate?31:19),r=ultimate?42:29;if(layer==='all'||layer==='front'){trail(c,skin,x,y,source,p,r,time,light);motif(c,skin,x,y,r,time);if(ultimate&&!light){ring(c,x,y,r*1.53,skin.accent,.74,.69,2,time*.3);ring(c,x,y,r*1.92,skin.main,.38,.75,1.5,-time*.4)}}}
else{phase=time<hit+.58?'Va chạm':'Thu về';impactT=clamp((time-hit)/(ultimate?1.16:.86));if(layer==='all'||layer==='front')impact(c,skin,target,impactT,time,ultimate,light);if(!light&&time<hit+.24)shake=Math.sin((time-hit)*80)*(1-(time-hit)/.24)*(ultimate?3.2:1.7)}
return{phase,fraction,release,hit,finish,impactT,shake};}
export {glow,ring,star};
