import LinhTam from './LinhTam'
import {useState} from 'react'
import SpiritArt from './SpiritArt'
const steps=[['Mở phòng','Chọn 1 đấu 1 (2 người) hoặc 2 đấu 2 (4 người), rồi gửi mã cho bạn. Đủ người, chủ phòng bắt đầu. Hai đội được chia xen kẽ theo thứ tự vào.'],['Làm câu Hoá','Mỗi lượt tự làm một câu đúng phần đã học. Tự trả lời đúng nhận 2 năng lượng; sai hoặc dùng trợ giúp chỉ được đứng yên, dựng khiên 5 giáp.'],['Chốt hành động','Chạm ô muốn đến hoặc đối thủ, rồi chọn một hành động. Mọi người chốt xong thì lượt được giải quyết.'],['Mang tinh thể về','Chỉ lượt đúng tự làm mới được nhặt hoặc giao Linh Tâm; đến ô có ♥ để nhặt, rồi hộ tống về mép căn cứ đội mình. Đưa đủ 2 tinh thể về là thắng!']]
const skills=[['Thạch Quy','Dựng tường','Chặn ô trống liền kề trong 2 lượt. Không dựng tại căn cứ hoặc ô có tinh thể.'],['Thuỷ Long','Lướt sóng','Đi 1 ô, thêm 10 giáp cho cả đội.'],['Viêm Sư','Đẩy lùi','Gây 30 sát thương và đẩy đối thủ lùi 1 ô; tầm tối đa 3 ô.'],['Phong Thố','Vượt đường','Nhảy tối đa 2 ô. Khi mang tinh thể chỉ đi 1 ô.'],['Tinh Lang','Bảo hộ','Thêm 25 giáp cho cả đội.'],['Ái Hồ','Hồi phục','Hồi 25 máu cho cả đội.'],['Ân Lộc','Tiếp sức','Đi 1 ô, hồi 20 máu cho đồng đội trong 2 ô.'],['Minh Linh','Toả sáng','Gây 15 sát thương lên đối thủ trong 3 ô, thêm 10 giáp cho cả đội.']]
export default function EscortGuide(){
 const [step,setStep]=useState(0)
 return <section className="escort-guide" aria-label="Hướng dẫn Hộ Tống Linh Tâm">
 <header><span className="eg-eyebrow">CÙNG HỌC · CÙNG HỘ TỐNG</span><h2>Cùng đồng đội đưa Linh Tâm về nhà.</h2><p>Hiểu cách chơi trong bốn bước — rồi rủ ba bạn vào trận.</p><div className="eg-badges"><b>2 đấu 2</b><b>2 tinh thể để thắng</b><b>Tối đa 8 phút · 12 lượt</b></div></header>
 <div className="eg-walkthrough"><div className="eg-steps" aria-label="Các bước chơi">{steps.map(([title,body],i)=><button key={title} type="button" aria-pressed={step===i} onClick={()=>setStep(i)}><span>{i+1}</span><div><strong>{title}</strong><p>{body}</p></div></button>)}</div>
 <figure className="eg-demo"><figcaption><b>Sân chơi nhìn từ trên xuống</b><span>Sơ đồ minh hoạ · chạm từng bước để xem</span></figcaption><div className={`eg-board eg-step-${step}`} role="img" aria-label="Sân 7 cột 5 hàng. Căn cứ Lam ở mép trái, Hồng ở mép phải; tinh thể ở giữa. Đưa tinh thể từ giữa về căn cứ của mình.">{Array.from({length:35},(_,i)=>{const pet=i===7?0:i===27?5:i===21?3:i===13?2:undefined;return <div key={i} className={`${i%7===0?'eg-blue':i%7===6?'eg-pink':''} ${step===3&&i>=14&&i<=17?'eg-route':''}`}>{pet!==undefined&&<SpiritArt index={pet} level={10}/ >}{i===17&&<LinhTam className="guide-heart"/>}{(i===2||i===32)&&<span className="eg-heal">✚</span>}{step===3&&i>=14&&i<17&&<span className="eg-arrow">←</span>}</div>})}</div><div className="eg-map-labels"><b>Căn cứ Lam</b><span>♥ Linh Tâm</span><b>Căn cứ Hồng</b></div><div className="eg-tip"><strong>{['Vào cùng bạn bè','Kiến thức tiếp năng lượng','Chọn rồi chốt','Cùng mở đường về nhà'][step]}</strong><p>{['Mỗi đội có hai thú. Trong trận, thú của em có nhãn EM.','Đúng và tự làm: +2 năng lượng. Hai đồng đội cùng đúng còn nhận thêm 10 giáp mỗi người.','Chỉ đúng tự làm mới được di chuyển. Dựng khiên không tốn năng lượng. Tung chưởng và kỹ năng riêng cần 2 năng lượng.','Đường mũi tên minh hoạ hướng về căn cứ Lam. Đội Hồng đưa tinh thể về mép phải.'][step]}</p></div></figure></div>
 <h3>Em làm gì trong một lượt?</h3><div className="eg-actions">{[['↗','Di chuyển','Miễn phí','Cần đúng tự làm. Đi 1 ô trống liền kề, theo chiều ngang hoặc dọc.'],['⬡','Dựng khiên','Miễn phí','Đúng tự làm: 20 giáp. Sai hoặc trợ giúp: 5 giáp. Tối đa 40 giáp.'],['✦','Tung chưởng','2 năng lượng','Gây 25 sát thương, tầm tối đa 3 ô.'],['✧','Kỹ năng riêng','2 năng lượng','Dùng tuyệt chiêu của thần thú đang đồng hành.']].map(([icon,title,cost,text])=><article key={title}><span>{icon}</span><b>{title}</b><small>{cost}</small><p>{text}</p></article>)}</div>
 <details className="eg-rules" open><summary>Luật cần nhớ trước khi vào trận</summary><div><p><b>60 giây mỗi lượt.</b> Chưa chốt khi hết giờ thì đứng yên, không nhận thêm giáp hay năng lượng. Mỗi lượt cần làm câu Hoá trước khi chốt một hành động.</p><p><b>Máu 100 cho mọi thú.</b> Cấp cao không tăng chỉ số chiến đấu. Hết máu: rơi tinh thể và hồi sinh tại căn cứ với 100 máu.</p><p><b>Phối hợp để mạnh hơn.</b> Hai bạn cùng tự làm đúng và cùng ở trong tầm 3 ô của một đối thủ sẽ liên kích, mỗi bạn gây 10 sát thương.</p><p><b>Đi đường ngắn, giữ đồng đội.</b> Người cầm tinh thể chỉ đi 1 ô. Ô ✚ hồi 10 máu cuối lượt. Khoảng cách tính theo ô ngang và dọc.</p><p><b>Thắng bằng hộ tống.</b> Đủ 2 tinh thể thắng ngay. Hết 8 phút hoặc 12 lượt, đội nhiều tinh thể hơn thắng; bằng nhau thì hoà.</p><p><b>Học vẫn được ghi nhận.</b> Trận đấu không sửa điểm thi, không trừ EXP. Câu Hoá lấy từ kho bài phù hợp với tiến độ của từng em.</p></div></details>
 <h3>Tám thần thú · tám cách phối hợp</h3><p className="eg-subtitle">Mỗi kỹ năng tốn 2 năng lượng. Chọn đúng lúc để mở đường hoặc cứu đồng đội.</p><div className="eg-skills">{skills.map(([name,title,text],i)=><article key={name}><SpiritArt index={i} level={10}/><div><small>{title}</small><h4>{name}</h4><p>{text}</p></div></article>)}</div>
 </section>
}
