import {useState} from 'react'
import {layDiaChiMayChu} from '../../lib/dia-chi-may-chu'
import {gioDayDu} from '../../lib/ngay-gio-24'
import {loadTeacherSecret} from '../../lib/exam-db'
interface Report {played:boolean;earned?:number;mastery:{dang:string;stage:number;due:number;distinct:number}[]}
export default function GameReports({teacher=false,sbd:initial=''}:{teacher?:boolean;sbd?:string}){
 const [sbd,setSbd]=useState(initial);const [pass,setPass]=useState('');const [report,setReport]=useState<Report|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [types,setTypes]=useState('');const [blocked,setBlocked]=useState('');const [enabled,setEnabled]=useState(true)
 const call=async(action:string,dang?:string)=>{if(busy)return;setBusy(true);setError('');try{const base=await layDiaChiMayChu('');const secret=teacher?await loadTeacherSecret():'';const r=await fetch(`${base}/${teacher?'game-v2-admin':'game-v2-parent'}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,sbd,pass,secret,maBiMat:secret,dang,types:types.split(/[,\s]+/).filter(Boolean),blocked:blocked.split(/[,\s]+/).filter(Boolean),enabled})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Chưa đọc được tiến bộ.');setReport(j.report);if(j.scope){setEnabled(j.scope.enabled);setTypes(j.scope.types.join('\n'));setBlocked(j.scope.blocked.join('\n'))}}catch(e){setError(e instanceof Error?e.message:'Lỗi kết nối.')}finally{setBusy(false)}}
 return <details className="rounded-2xl border border-slate-200 bg-white p-4 text-slate-900"><summary className="cursor-pointer font-bold">Tiến bộ Hoá trong Thần Thú</summary><div className="space-y-3 pt-4"><p className="text-sm">{teacher?'Xem bằng chứng đã tự làm, ngày ôn tiếp và giới hạn phần luyện của từng em.':'Nhập mã do con chia sẻ trong game, mục Tiến bộ của em. Mã này chỉ mở báo cáo game.'}</p>{teacher?<input className="border rounded p-2" aria-label="SBD xem tiến bộ" value={sbd} onChange={e=>setSbd(e.target.value)} placeholder="Số báo danh"/>:<input className="border rounded p-2 w-full" aria-label="Mã xem tiến bộ game" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Mã xem tiến bộ"/>}<button className="rounded bg-teal-700 text-white px-4 py-2" disabled={busy} onClick={()=>void call('report')}>Xem tiến bộ</button>{error&&<p role="alert" className="text-red-700">{error}</p>}{report&&<><p>{report.played?`EXP mới: ${report.earned??0}.`:'Chưa có lượt chơi phiên bản mới.'}</p>{report.mastery.map(m=><div key={m.dang} className="rounded border p-3 text-sm"><strong>{m.dang.length>40?'Câu chưa có mã dạng':m.dang}</strong><p>{['Cần ôn','Đã sửa câu','Đã làm câu mới','Đã kiểm tra lại sau 7 ngày'][m.stage]} · {m.distinct} câu khác nhau</p><p>Ôn tiếp: {gioDayDu(m.due,'chưa rõ')}</p>{!teacher&&m.dang.length<40&&<button className="border rounded p-2" disabled={busy} onClick={()=>void call('task',m.dang)}>Nhắc con ôn dạng này</button>}</div>)}{teacher&&<div className="space-y-2"><label className="flex gap-2"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Cho phép chơi game</label><p className="text-sm">Chỉ luyện các mã dạng dưới đây; để trống thì theo lịch sử đã học. Không mở phần chưa học.</p><textarea className="border p-2 rounded w-full" aria-label="Mã dạng được luyện" value={types} onChange={e=>setTypes(e.target.value)}/><p className="text-sm">Các mã câu cần loại khỏi game:</p><textarea className="border p-2 rounded w-full" aria-label="Mã câu loại khỏi game" value={blocked} onChange={e=>setBlocked(e.target.value)}/><button className="rounded bg-teal-700 text-white px-4 py-2" disabled={busy} onClick={()=>void call('scope')}>Lưu phạm vi game</button></div>}</>}</div></details>
}
