# Self-contained screenshot review; no application code, requests, or external assets.
from pathlib import Path
from PIL import Image
from io import BytesIO
import base64,json
src=Path('/workspace/bat-linh-preview')
cases=[
('Biểu cảm và xe mới','bieu-cam-390.png'),('Học sinh · Sảnh','sanh-390.png'),('Học sinh · Hoàn thành ngày','xong-390.png'),('Đăng nhập học sinh','hs-login-390.png'),
('Tự luyện · Chọn chế độ','tl-390.png'),('Tự luyện · Câu hỏi','luyen-cau-hoi-390.png'),('Tự luyện · Kết quả câu','luyen-ket-qua-390.png'),('Tự luyện · Tổng hợp','luyen-tong-hop-390.png'),('Câu đã làm','cau-da-lam-390.png'),
('Đảo · Bản đồ','dao-390.png'),('Đảo · Câu hỏi','dao-cau-hoi-390.png'),('Đảo · Lời giải','dao-loi-giai-390.png'),('Chọn thần thú','than-thu-chon-390.png'),('Đảo cá nhân','than-thu-dao-390.png'),('Sổ tay','than-thu-so-tay-390.png'),('Túi đồ','than-thu-tui-390.png'),
('Hộ tống · Sảnh','ho-tong-sanh-390.png'),('Hộ tống · Hết câu hôm nay','ho-tong-sanh-het-390.png'),('Hộ tống · Trận và xe mới','ho-tong-tran-390.png'),('Hộ tống · Trùm','ho-tong-trum-390.png'),('Hộ tống · Kiến thức cốt lõi','ho-tong-cot-loi-390.png'),('Hộ tống · Lời giải','ho-tong-ket-qua-390.png'),('Hộ tống · Tiếp sức','ho-tong-tiep-suc-390.png'),('Hộ tống · Thắng','ho-tong-thang-390.png'),('Hộ tống · Chưa thắng','ho-tong-thua-390.png'),('Tung chưởng · Thường','tung-chuong-390.png'),('Tung chưởng · Trùm','tung-chuong-trum-390.png'),
('Cửa hàng','shop-390.png'),('Thử đồ','thu-do-390.png'),('Tủ đồ','tu-do-390.png'),('Bi-a Phản Ứng','bia-390.png'),('Đăng nhập phụ huynh','ph-login-390.png'),('Phụ huynh · Tổng quan','ph-390.png'),('Phụ huynh · Điểm','ph-diem-390.png'),('Phụ huynh · Tiến bộ','ph-tien-bo-390.png'),('Phụ huynh · Lời thầy','ph-loi-thay-390.png'),('Phụ huynh · Báo cáo chi tiết','ph-chi-tiet-390.png')]
rows=[]
for title,name in cases:
 im=Image.open(src/name);o=BytesIO();im.save(o,format='WEBP',quality=82,method=4)
 rows.append([title,'data:image/webp;base64,'+base64.b64encode(o.getvalue()).decode()])
atlases=['data:image/webp;base64,'+base64.b64encode(Path(f'public/bat-linh/bieu-cam-{n}.webp').read_bytes()).decode() for n in [1,2]]
html='''<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bát Linh · Xem ngoại tuyến</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f3e7;color:#214e43;font:15px system-ui,sans-serif}header{padding:20px;background:#fffcf2;border-bottom:1px solid #d9cda8}h1{font:700 26px Georgia,serif;margin:0 0 8px}p{line-height:1.6}select,button{font:inherit;border:1px solid #c5b785;border-radius:12px;padding:12px;background:#fffdf4;color:#214e43;max-width:100%;cursor:pointer}nav{position:sticky;top:0;padding:12px;background:#f4f3e7;display:flex;gap:8px;flex-wrap:wrap;border-bottom:1px solid #e0d8c1;z-index:2}main{max-width:1000px;margin:auto;padding:16px;text-align:center}#screen{display:block;width:390px;max-width:100%;height:auto;margin:auto;border-radius:20px;border:1px solid #ddd2b1}#faces{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:14px;margin:20px auto}article{background:#fffcf2;padding:18px;border:1px solid #e0d8c1;border-radius:20px}.portrait{display:block;margin:auto;width:120px;height:120px;background-size:600% 400%;border:2px solid #d4b66c;border-radius:32%;box-shadow:0 3px 12px #18463722}.note{font-size:13px;color:#617768}button[aria-pressed=true]{background:#246b57;color:white}#emotes[hidden],#gallery[hidden]{display:none}
</style><header><h1>Bát Linh · Phòng duyệt giao diện</h1><p>37 ảnh chụp màn hình + 48 nét mặt cho 8 thần thú. Tất cả hình nằm trong tệp này, mở được khi không có Internet.</p><p class="note">Đây là bản xem thiết kế bằng ảnh, không phải app chạy thật. Trong phần biểu cảm có thể bấm đổi trạng thái. Chưa cập nhật máy chủ ứng dụng.</p></header><nav><select id="choose" aria-label="Chọn màn"></select><button id="facesButton">Thử 48 biểu cảm</button></nav><main><section id="gallery"><h2 id="title"></h2><img id="screen" alt=""></section><section id="emotes" hidden><h2>Tám người bạn · Sáu nét mặt</h2><div id="states"></div><div id="faces"></div><p class="note">Trong app, nét mặt hiện ở khung cận cảnh cạnh thú; hình toàn thân vẫn theo cấp tiến hoá.</p></section></main><script>const rows=ROWS;const atlases=ATLASES;
const sel=document.querySelector('#choose'),img=document.querySelector('#screen');rows.forEach(([name],i)=>{const o=document.createElement('option');o.value=i;o.textContent=name;sel.append(o)});function show(i){document.querySelector('#gallery').hidden=false;document.querySelector('#emotes').hidden=true;img.src=rows[i][1];img.alt=rows[i][0];document.querySelector('#title').textContent=rows[i][0]}sel.onchange=()=>show(+sel.value);show(0);
const names=['Thạch Quy','Thuỷ Long','Viêm Sư','Phong Thố','Tinh Lang','Ái Hồ','Ân Lộc','Minh Linh'],states=['Chào đón','Suy nghĩ','Vui khi đúng','Động viên khi sai','Quyết tâm','Ăn mừng'];names.forEach((n,i)=>{const a=document.createElement('article'),face=document.createElement('span'),h=document.createElement('h3');h.textContent=n;face.className='portrait';face.style.backgroundImage='url('+atlases[i<4?0:1]+')';face.dataset.row=i%4;a.append(face,h);document.querySelector('#faces').append(a)});function emotion(j){document.querySelectorAll('.portrait').forEach(f=>f.style.backgroundPosition=(j*20)+'% '+(+f.dataset.row*100/3)+'%');document.querySelectorAll('#states button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===j)))}states.forEach((s,j)=>{const b=document.createElement('button');b.textContent=s;b.style.margin='4px';b.onclick=()=>emotion(j);document.querySelector('#states').append(b)});emotion(0);document.querySelector('#facesButton').onclick=()=>{document.querySelector('#gallery').hidden=true;document.querySelector('#emotes').hidden=false};</script></html>'''
html=html.replace('ROWS',json.dumps(rows,ensure_ascii=False)).replace('ATLASES',json.dumps(atlases))
p=Path('/workspace/bat-linh-preview/Bat-Linh-Xem-Giao-Dien.html');p.write_text(html);print(len(rows),'screens;',p.stat().st_size,'bytes;',p)
